---
- name: Installing necesseri packages 
  hosts: all
  become: yes
  tasks:
    - name: Update repositories cache and install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - neofetch 
