---
- name: Installing necesseri packages 
  hosts: pc 
  become: yes
  tasks:
    - name: Update repositories cache and install  packages
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - vim 
        - tmux
        - git 
        - net-tools
        - curl 
        - ufw
        - apt-transport-https
        - ca-certificates
        - curl
    - name: installa dipendenze
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: aggiungi chiave GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: aggiungi repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: installa docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io  

    - name: assicurati che docker sia attivo
      service:
        name: docker
        state: started
        enabled: yes

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted
          - gnupg-agent
          - software-properties-commondocker 
 #sudo groupadd docker
    - name: Create "docker" group
      group:
        name: docker
        state: present
    
 #sudo usermod -aG docker root
    - name: Add remote "ubuntu" user to "docker" group
      user:
        name: artmiss
        group: docker
        append: yes
